/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 25, 2018 at 11:23:34 PM Eastern European Standard Time
* Operating System: Version 11.1.2 (Build 15B202)
* Image Source: /System/Library/PrivateFrameworks/BluetoothManager.framework/BluetoothManager
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

typedef struct BTDeviceImpl* BTDeviceImplRef;

typedef struct _NSZone* NSZoneRef;

typedef struct {
	BOOL field1;
	BOOL field2;
	BOOL field3;
	BOOL field4;
} SCD_Struct_Bl2;

typedef struct BTLocalDeviceImpl* BTLocalDeviceImplRef;

typedef struct BTSessionImpl* BTSessionImplRef;

typedef struct BTDiscoveryAgentImpl* BTDiscoveryAgentImplRef;

typedef struct BTPairingAgentImpl* BTPairingAgentImplRef;

typedef struct BTAccessoryManagerImpl* BTAccessoryManagerImplRef;

