/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 25, 2018 at 11:23:34 PM Eastern European Standard Time
* Operating System: Version 11.1.2 (Build 15B202)
* Image Source: /System/Library/PrivateFrameworks/BluetoothManager.framework/BluetoothManager
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_xpc_object;
@class NSObject;

@interface RemoteDeviceManager : NSObject {

	NSObject*<OS_xpc_object> _connection;

}
-(id)init;
-(void)dealloc;
-(void)sendMessage:(const char*)arg1 args:(id)arg2 ;
-(void)disconnectDevice:(id)arg1 ;
@end

